- src/structures/MessagePayload.js
- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
> revert embeds, add webembed as optional

- src/util/Options.js
> fix: set `checkUpdate` to `false` by default

- src/managers/MessageManager.js
https://github.com/aiko-chan-ai/discord.js-selfbot-v13/issues/203#issue-1304978048
> Fix channel.messages.fetch throw 'Missing Access'

- src/managers/RelationshipsManager.js
for cancelling friend requests.
> feat(RelationshipsManager): new cancelFriendRequest method

- src/structures/Guild.js
- typings/index.d.ts
https://github.com/discordjs/discord.js/pull/8423
> feat(Guild): Add `max_video_channel_users`

- src/structures/Guild.js
> chore: fix eslint.

- package.json
- src/managers/ClientUserSettingManager.js
> fix(ClientUserSettingManager): data.guild_positions return undefined

- src/structures/User.js
- src/structures/interfaces/TextBasedChannel.js
> fix(SendSlash): BotId !== applicationId

- src/structures/ApplicationCommand.js
- typings/index.d.ts
- Refactor code
- Add `sendContextMenu` :v
> feat: Appliaction

- src/structures/ClientUser.js
> fix(ClientUser): Bio is null

- package.json
- src/client/actions/WebhooksUpdate.js
- src/errors/Messages.js
- src/managers/GuildChannelManager.js
- src/managers/GuildForumThreadManager.js
- src/managers/GuildTextThreadManager.js
- src/managers/ThreadManager.js
- src/structures/BaseGuildTextChannel.js
- src/structures/CategoryChannel.js
- src/structures/Channel.js
- src/structures/ForumChannel.js
- src/structures/Guild.js
- src/structures/GuildChannel.js
- src/structures/Message.js
- src/structures/MessagePayload.js
- src/structures/PartialGroupDMChannel.js
- src/structures/ThreadChannel.js
- src/structures/Webhook.js
- src/structures/WelcomeChannel.js
- src/util/ChannelFlags.js
- src/util/Constants.js
- src/util/Util.js
- typings/index.d.ts
https://github.com/discordjs/discord.js/pull/8651
> feat: Guild Forum channel

- src/client/Client.js
- typings/index.d.ts
> feat: switch user

- src/structures/interfaces/TextBasedChannel.js
- typings/index.d.ts
🐛 fix(TextBasedChannel.js): change send method name from send to send Slash 
🐛 fix(index.d.ts): change applicationId parameter type from ApplicationCommandTypes to Snowflake in searchInteraction method
> 🐛 fix(types)

- src/structures/interfaces/TextBasedChannel.js
Fixed documentation code block (missed closing quotes)
> Fixed TextBasedChannel.js documentation (non urgent)

- src/structures/ClientUser.js
Fixed setUsername function in ClientUser.js
> setUsername Fix, new Username System

- src/structures/ClientUser.js
Updated ClientUser.js
tested the method with success.
+ Pronouns Support
+ setPronouns Method
```
if ('pronouns' in data) {
this.pronouns = data.pronouns;
}
```
&&
```
/**
* Set pronouns
* @param {string | null} pronouns
* @returns {Promise<ClientUser>}
*/
setPronouns(pronouns = '') {
return this.edit({ pronouns });
}
```
> Added Pronouns support

- src/managers/MessageManager.js
I believe that this log shouldn't be there?
> fix(message_manager): remove unnecessary log

- src/errors/Messages.js
- src/structures/VoiceState.js
- typings/index.d.ts
I checked the api and it should work in theory but I don't have an alt to test in practice
> feat (VoiceState) add setStatus function

- src/client/Client.js
- src/client/websocket/WebSocketShard.js
- src/rest/APIRequest.js
since proxy-agent v 6 no longer working due its package and need multiple packages
i've downgraded to v5 and it works fine
> downgrade proxy-agent to version 5 

- src/managers/GuildForumThreadManager.js
This is my fix 🛠️ for [Issue #1126](https://github.com/aiko-chan-ai/discord.js-selfbot-v13/issues/1126)
Just a slight change to the object creation for making a forum post cleans this right on up. 👍🏻
> Issue #1126 fix `data` initialization error

- src/client/BaseClient.js
fix: #1120 
I don't think it is gonna working ;-;
> fix(client): handle promise rejections

- src/structures/Presence.js
> fix(client): CustomStatus don't working

- src/client/Client.js
- src/errors/Messages.js
- src/util/Totp.js
- typings/index.d.ts
TOTP code is copied from [totp-generator](https://github.com/bellstrand/totp-generator) npm package to minimize dependency bloat
> feat: add mfa code completion from TOTP key

- src/managers/RelationshipManager.js
> fix(RelationshipManager): change sendFriendRequest to hopefully reduce account bans

- src/managers/RoleManager.js
- src/structures/Role.js
- typings/index.d.ts
RoleManager.fetchMemberCounts
RoleManager.fetchMemberIds
Role.fetchMemberIds
> Added the ability to fetch role member counts and member ids for single roles
